language: node_js
node_js:
- stable
branches:
  only:
  - source

install: npm install

before_script:
- git config --global user.name "HanyangOSORI"
- git config --global user.email "hanyangosori@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
- hexo clean
- hexo g
- hexo d